---
# tasks file for /Users/manuelbarraganarevalo/Projects/securitas/new_physical_deployment
- name: Copy dynamic motd template
  template:
    src: /Users/manuelbarraganarevalo/Projects/securitas/test.j2
    dest: /Users/manuelbarraganarevalo/Projects/securitas/test.yml
  become: yes