---
# tasks file for /Users/manuelbarraganarevalo/Projects/securitas/new_physical_deployment
- name: "include host vars"
  include_vars:
    file: "{{ ansible_hostname }}.yml"
- name: Copy dynamic motd template
  template:
    src: elastic.jinja
    dest: /Users/manuelbarraganarevalo/Projects/securitas/{{ item }}/test.yml
  loop: "{{ nodes }}"
